# Generated by Django 3.2.9 on 2021-11-22 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cmsmetatags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsmetatags',
            name='tw_description',
            field=models.TextField(blank=True, default='', help_text='If empty, Facebook description is shown', max_length=355, verbose_name='Twitter description'),
        ),
        migrations.AddField(
            model_name='cmsmetatags',
            name='tw_image',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmsmetatags_tw_image_set', to=settings.FILER_IMAGE_MODEL, verbose_name='Twitter image'),
        ),
        migrations.AddField(
            model_name='cmsmetatags',
            name='tw_title',
            field=models.CharField(blank=True, default='', help_text='If empty, Facebook title is shown', max_length=255, verbose_name='Twitter title'),
        ),
        migrations.AlterField(
            model_name='cmsmetatags',
            name='fb_description',
            field=models.TextField(blank=True, default='', help_text='If empty, meta description is shown', max_length=355, verbose_name='Facebook description'),
        ),
        migrations.AlterField(
            model_name='cmsmetatags',
            name='fb_title',
            field=models.CharField(blank=True, default='', help_text='If empty, page title is shown', max_length=255, verbose_name='Facebook title'),
        ),
        migrations.AlterField(
            model_name='cmsmetatags',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='SEO description, defaults to page->settings->meta description', max_length=355, verbose_name='Meta description'),
        ),
    ]
